:toc: macro
:sectlinks: 2
:toclevels: 5

= Scribble Nib

A tabletop RPG
inspired by
Maze Rats,
ICRPG,
Fellowship 2E,
Mausritter,
Cairn,
and
Knave.

toc::[]

= Character Creation

== Choose Stats

Assign +0, +1, and +2 to your stats in any order.

* **Strength (STR):** brawn, toughness, and vigor
* **Dexterity (DEX):** agility, reflexes, and swiftness
* **Will (WIL):** force of personality and persuasion

You also have a base **Armor** of +0,
which will increase when you select your starting equipment;
and no **Grit**, which is used to protect stats when taking damage.
You gain Grit starting at 2nd level.

== Choose Training

Training gives you Advantage on rolls related to certain tasks.
Choose training in one of the following areas.

* **Athletics:** Climbing, leaping, balancing
* **Stealth:** Sneaking, hiding, disguises
* **Survival:** Tracking, foraging, navigating wilderness
* **Thievery:** Tinkering, picking locks and pockets

== Choose Starting Equipment

Your starting equipment is:

* A melee weapon of your choice
* A shield (+1 Armor) or ranged weapon of your choice
* Leather armor (+1 Armor) or a random spellbook
* A sack or backpack that provides 8 pack slots
* A belt that provides 2 strap slots
* 3 Gear
* 3 Supplies

Roll or choose your Gear and Supplies using the tables in the Equipment
section.

//The GM may have you start with an Heirloom or Legacy.

== Inventory

You have 16 item slots.

* 2 hand slots for items you are holding and using
* 2 strap slots for items that can be freely swapped with hand slots
* 4 body slots for armor and worn magic items
* 8 pack slots for items that take an action to find

Most items take up one item slot.
Large items such as two-handed weapons and full suits of armor take up two slots.
Small items such as arrows and coins can be bundled together in one slot.

== Levels

[cols="1,1"]
|===
| Level | Features Gained

| 1
| Stats, training, equipment, inventory

| 2
| +1 Grit

| 3
| +1 to a stat bonus

| 4
| +1 Grit

| 5
| +1 Grit

| 6
| +1 to a stat bonus

| 7
| +1 Grit
|===

Player characters (PCs) gain levels whenever a Milestone is reached.
The game master (GM) will determine when that is.

= Rules Summary

== Rolls

If the GM asks for a STR, DEX, WIL, or Armor roll,
roll a d20, add the appropriate bonus,
and compare it against the Difficulty.
A roll that meets or exceeds the Difficulty is a success,
which means you accomplish what you set out to do.
An unsuccessful roll will be interpreted and described by the GM.

== Difficulty

The GM sets a global Difficulty and adjusts it as the situation changes.
The Difficulty is shown to the players at all times.

== Advantage

The GM may decide that a player character
has Advantage or Disadvantage on a roll due to their circumstances.
To roll with Advantage, roll two d20s and take the highest roll.
To roll with Disadvantage, take the lowest roll.

Advantage cancels Disadvantage.
Only roll one d20 if you have both.

= Combat

== Turns

Players who make a DEX roll take their first turn before the GM.
Then the GM takes their turn,
and play proceeds to the GM's left after that.

== Attacking

PCs roll STR when attacking in melee
and DEX when attacking at range.
Some magic attacks use WIL instead of STR or DEX.

== Defending

Enemies may attack on the GM's turn.
PCs roll Armor to defend against attacks.
Some magic attacks are defended against using WIL instead of Armor.
If the roll is unsuccessful, the PC takes damage.

== Damage

On a hit, the target chooses one undamaged Grit
or an undamaged STR, DEX, or WIL stat to take damage.
Rolls made with damaged stats have Disadvantage.
Rolls that PCs make against enemies have Advantage
if the target has a damaged stat.

If a PC or enemy takes damage
while all their Grit and stats are already damaged,
they fall unconscious.
Damage taken while unconscious means instant death.

When a PC dies,
the player can create a new character or take over a hireling.
To avoid downtime, they rejoin the group as soon as they're ready.

== Healing

Once each morning, afternoon, and night,
you can tend to your health
(bandage a wound, take a dose of medicine, etc.)
to heal one Grit.

Once each morning and afternoon,
you can eat a meal and rest to heal one Grit.

Once each night,
you can get sleep for 6 hours to heal all Grit and one stat.

//= Narrative Combat
//
//The players describe how they contribute to the fight.
//The GM asks each of them to roll STR, DEX, or WIL
//depending on what they described.
//Each PC takes damage from an enemy unless they beat the Difficulty.
//
//The player with the highest successful roll describes how the fight was won.
//If no roll was a success, the GM describes the outcome of the fight.

= Equipment

// Food: 1-5gp

**Supplies:** _1-5gp_

. Antitoxin
. Arrows
. Bear Repellent
. Caltrops
//. Chalk
. Glue
. Grease
. Incense
. Ink
. Medicine
. Nails
. Oil
. Rations
//. Salve
. Salt
. Sealant
. Soap
. Tar
. Torch
. Vial of Acid
. Vial of Poison
. Waterskin

**Gear:** _5-10gp_

. Bear Trap
. Bucket
. Chain
. Crowbar
. Dowsing Rod
. Grappling Hook
. Hammer
. Horn
. Lockpicks
. Manacles
. Metal File
. Net
. Pick
. Pitons
. Pole
. Rope
. Saw
. Shovel
. Spyglass
. Tinderbox

**Weapons & Armor:** _10-50gp unless otherwise noted_

. Bow
. Crossbow
. Sling
. Axe
. Dagger
. Flail
. Halberd
. Longsword
. Mace
. Short Sword
. Spear
. War Hammer
. Shield (+1 Armor)
. Helmet (+1 Armor)
. Gambeson (+1 Armor)
. Brigandine (+1 Armor)
. Padded Armor (+1 Armor)
. Leather Armor (+1 Armor)
. Chainmail (+2 Armor, 400gp)
. Platemail (+3 Armor, 1000gp)

// Luxury Items: 50-100gp

// Exotic Goods: 100-1000gp

= GMing

== Managing Difficulty

This game has a single Difficulty (DC) that varies as the PCs' situation changes.
It's set by the GM and shown to the players at all times.

This is done to speed up gameplay and make it easier to run the game.
Players always know what number they're rolling against,
and the GM doesn't have to think of a DC for every action a player takes or
monster they might encounter.
Instead, the GM simply thinks of a DC
representing how hard or easy the current scenario is,
and displays it in a prominent location with a post-it or a d20.

A simple rule of thumb is to use
Difficulty 12 in relatively safe areas such as towns or a home base,
Difficulty 15 in unsafe areas such as dungeons and wilderness,
and Difficulty 18 in areas with villainous or world-ending threats.

== Monsters

This game is designed to make it easy to create monsters on the fly.
Since PCs roll to attack and also to defend,
monsters never need to roll and don't need bonuses assigned to their stats.
Since PCs always roll against the Difficulty,
monsters never need a monster-specific
"target number" or "difficulty class" to roll against.

A monster's stat block is just its name, stats, Grit,
and any abilities it has.
Stats and Grit are represented with checkboxes.
For example, a bear's stat block is _"Bear ☐☐☐☐"_.
The leftmost three checkboxes represent the monster's stats
and other checkboxes represent Grit.
The GM ticks off checkboxes from right to left as the monster takes damage.

Unlike PCs, monsters can have fewer than three stats.
For example, a goblin's stat block might be _"Goblin ☐"_.
A particularly weak stat block such as _"Goblin Minion"_ might have no stats,
in which case the monster is knocked out with a single hit.

In addition to a name, stats, and Grit, monsters can have abilities.
Here are some example stat blocks with abilities.

**Vampire** ☐☐☐::
Heals one stat when dealing damage with its bite.
Regenerates in its coffin when killed unless staked through the heart.

**Troll** ☐☐☐☐::
Regrows one limb and heals one stat at the end of its turn.

**Dragon** ☐☐☐☐☐☐☐☐☐::
Flies and breathes fire.

== Milestones

The GM can set milestones in whatever way they see fit.
This is so that the rate of the party's progression
can match the desired pace of the campaign.
Some possible ways to set milestones include:

* At specific story beats
* After each boss encounter
* Whenever the party finds a treasure hoard
* At the end of each session

== Magic

=== Spellbooks

Each spellbook occupies a single inventory slot,
and contains a single spell.
Spells and spellbooks can't be copied or created.

The details of each spell vary greatly,
including how to cast them.
Some spellbooks must be held firmly with both hands and read aloud,
while others must simply be on your person and activated with a gesture.
Some spells called _cantrips_ can be activated over and over,
while others must be recharged after one or several uses.
Spells might take a moment, a few seconds, or minutes to cast.
They might require a source of power such as a wand or holy symbol.
The most powerful spells, called _rituals_,
can take hours or even days spent in concentration performing the proper
rites using exotic materials that are consumed by the spell.

Spells are fickle and unpredictable.
If a spell instructs you to roll as part of casting it,
rolling a natural 1 can cause damage, disfiguration,
or have other unintended consequences.

=== Spells

Although spell lists from other games can be adapted for use in this one,
the GM is encouraged to design spells improvisationally.
One way of doing that is the three-step process outlined below.

First, say **what it's called**.
Choose a name for the spell if you have one in mind,
or use a spell name generator such as the one from Maze Rats.

Then, say **how it works** and **what it is**.
State as concisely as possible how the player casts the spell
and its sensory effects --
what it looks like, sounds like, smells like, etc.

Take a deliberate pause and think through next step.
A moment's thought can help you catch undesireable consequences of your
design,
allowing you to quickly work a casting condition into the spell,
make it recharge,
give it some other limitation,
or pivot to another design.

Lastly, say **what it does**.
Briefly outline how the spell impacts the world around it.
In other words, make a ruling on what the effects of the spell are.

Each step of the process informs the next,
and you should say each step out loud before thinking about the next.
The goal is to create spells on the fly, conversationally and
improvisationally, without interrupting the flow of the game.

Since you're creating the spell conversationally,
it's okay if the effects of the spell are vague at first.
Players will naturally ask questions about ambiguous details,
and in answering them,
you will create additional rulings that describe how the spell works.

This method works for creating magic items and custom abilities, too.

=== Magic Items

A magic item is an object with a spell woven or forged into it.
The process for designing one is largely the same as for a spell.

=== Relics

//== Loot

= Optional Rules

//== Spellcraft
//
//[cols="1,2,2,2,2,1,1,1,1,1,1,1"]
//|===
//.2+| **Type** 4+| **Requirement** 7+| **Effect**
//| **Materials**
//| **Condition**
//| **Conveyance**
//| **Risk**
//| **Duration**
//| **Range**
//| **Area**
//| **Subjects**
//| **Weight**
//| **Force**
//| **Energy**
//
//| Cantrip
//| Source of power (wand, holy symbol, etc.)
//| None
//| A moment and a word or gesture
//| An unsuccessful roll
//| A few minutes
//| Arm's reach
//| Closet
//| One
//| Cat
//| Push
//| Candle
//
//| Minor Spell
//| One common ingredient per casting
//| Something common yet specific such as attacking or being attacked
//| A few seconds and a phrase and/or gesticulation
//| Damage or disfiguration to yourself
//| Half an hour
//| Throwing distance
//| Room
//| Several
//| Horse
//| Weapon strike
//| Bonfire
//
//| Major Spell
//| Several uncommon ingredients per casting
//| A specific time of the day or other uncommonly encountered circumstance
//| A few minutes, an incantation, and a gesticulation
//| Damage or disfiguration to several allies and/or passersby
//| A few hours
//| Sight
//| Field
//| Several dozen
//| Carriage
//| Cannonball
//| Forest fire
//
//| Ritual
//| Many exotic ingredients per casting
//| A specific phase of the moon, day of the year, or other rare occurrence
//| Hours spent in concentration performing the proper rites
//| Adventure- or campaign-spanning consequences
//| A day
//| A few hundred miles
//| City
//| Hundreds
//| Ship
//| Meteor
//| Volcano
//|===

//spell systems
//--
//spell types: cantrips, spells, rituals, etc.
//magic types: alchemy, artifice
//all systems require a focus
//wild mage: default system
//godbotherers: patrons of powerful beings, prepend spell with [NAME]'s
//specialist mage: lock one aspect
//spellweaving: cast arbitrary spells, takes longer, other costs sometimes
//--
//barbarians of lemuria: cantrips, first/second/third magnitude w/ example spells
//wonder & wickedness: levelless spell list
//Beyond the Wall and other adventures: cantrip/spell/ritual w/ spell list
//Jaws of the Six Serpents: sorcery/charms/alchemy/divination w/ effects table
//mini six simpler magic system: effect lists similar to jotss effects table
//* https://forum.rpg.net/index.php?threads/mini-six-simpler-magic-system.531361/
//ars magicka hacked for fudge: 4 actions x 5 realms give 20 effects
//* https://www.reddit.com/r/rpg/comments/36je3s/quick_easy_freeform_magic_system_for_a_single/crf1cuf/
//
//spell types: cantrips, spells, rituals
//magic types: alchemy, artifice
//
//scroll/potion of ____: contains one spell
//wand of ____: change one spell aspect into ____
//spellweaver's hooks: expend spell slot to create random spell, modify 1/round
//
//godbotherers: patrons of powerful beings, prepend spell with [NAME]'s
//--
//focus: holy symbol
//need separate good/holy/nature tables?

== Character Creation: Additional Training

If the setting and campaign support it,
the GM may wish to make the following training available
at character creation
or through mentors that the PCs meet during their adventures.

* **Academics:** History, lore, esoteric knowledge
* **Seafaring:** Sailing, swimming, ocean navigation
* **Witchcraft:** Medicine, herbalism, alchemy

GMs can, of course,
work with the players to create training for a specific character concept.
A retired chef adventurer might have the following training, for example.

* **Cooking:** Baking, sauteing, grilling

== Character Creation: Custom Abilities

The default assumption is that characters are ordinary humans
whose exceptional abilities come from magic items found in loot.
But for playgroups that want characters with inherent exceptional abilities,
PCs may gain a Starting ability at 1st level,
an Improved ability at 4th level,
and an Ultimate ability at 7th level.

The gamemaster discusses with the players to determine their abilities.
Here is an example of how such a discussion might go:

[quote]
----
GM: Okay, let's figure out an ability for your character. What's the
one special thing that they're good at?

Player: I want my character to be able to befriend any animal.

GM: Okay, that sounds pretty powerful. I think you would steamroll the
dungeon I have planned if you just strolled in with a bunch of panther and
bear friends. Maybe that could be your ultimate ability. Your starting
ability could be that you can befriend any cat-sized or smaller animal.
How does that sound?

Player: Sure, that's great!

GM: Okay, cool. And your improved ability can be that you instantly
befriend animals as large as a deer. Does that work?

Player: Yeah!

GM: Alright, and how does befriending an animal work exactly? What do
you do to befriend them?

Player: I was thinking I would just talk to them?

GM: Oh neat, yeah that works. So your starting ability is that you can talk to
animals and befriend any cat-sized or smaller animal that you talk to. And
later on you'll be able to befriend deer-sized animals, and later still you
can befriend any animal. Sounds good!
----

Some example abilities are below.

**Animal Friendship**:
You can talk to animals.
You befriend cat-sized or smaller animals when you talk to them. +
**Improved Animal Friendship**:
You befriend deer-sized or smaller animals when you talk to them. +
**Ultimate Animal Friendship**:
You befriend any animal you talk to.

**Surprise Attack**:
You add 1d6 to attack rolls made against surprised enemies. +
**Improved Surprise Attack**:
You deal +1 damage to surprised enemies. +
**Ultimate Surprise Attack**:
You add another 1d6 to attack rolls and another +1 damage against surprised
enemies.

**Critical Strike**:
You deal massive damage on a critical strike.
After rolling a natural 20 on an attack roll,
you roll another attack roll and deal damage if it hits.
If the attack roll is a critical strike, the process repeats. +
**Improved Critical Strike**:
When you have advantage on an attack roll,
a natural 19 triggers a critical strike in addition to a natural 20. +
**Ultimate Critical Strike**:
A natural 19 on an attack roll is a critical strike
regardless of whether or not you have advantage.

//=== Custom Ability Variants: Magic Systems

//Magic is fickle, mysterious, and dangerous.

//Wild Magic

//Specialist Magic

//Domain Magic

//Artifice & Spellcraft

//=== Custom Ability Variants: Milestone Abilities

//=== Custom Ability Variant: Legacies

//== Endgame Play: Additional Levels

//== Endgame Play: Retirement & Heirlooms

== Combat: More Healing

The following addition to the <<Healing>> rules
might be appropriate for campaigns with few magical sources of healing.
It also makes potable water an important resource.

After an encounter,
a PC that was damaged in the encounter can catch their breath for 5 minutes
and drink fresh water to heal one Grit.

== Combat: Freeform Combat

GMs may wish to forego <<Turns>> and run combat conversationally,
the same way the game is run outside of combat.
In that case, the GM should strive to ensure that everyone at the table
gets a chance to participate in each encounter.

//== Combat: Hit Points
//
//The following are alternative rules for combat
//based on health and damage dice instead of Grit and stat damage.

//=== Armor & Health
//
//You start with 4 max health
//Instead of Grit, you gain +2 max health at even levels.
//Shields, chestplates, leggings, and similar protection
//provide 1 Armor each, to a maximum of 3.
//Armor reduces damage.
//
//=== Damage & Attacking
//
//To attack, roll damage and subtract the target's Armor.
//The target loses that much health.
//
//* **Unarmed:** Fists deal **d4** damage
//* **Weapon:** Weapons deal **d6** damage
//* **Magic:** Magic deals **d8** damage
//* **Ultimate:** Exceptional attacks add **d12** to the damage
//
//At 0 health, a PC falls unconscious.
//When a PC reaches negative health,
//they die in 1d4 turns unless stabilized with healing.
//
//When a PC dies,
//the player can create a new character or take over a hireling.
//To avoid downtime, they rejoin the group as soon as they're ready.
//
//=== Healing
//
//Once per hour, you can rest for 5 minutes
//and drink fresh water to heal 2 health.
//
//Once per day, you can take a dose of medicine
//to heal 2 health.
//
//Once per day,
//you can eat a meal
//and sleep in a safe place for 6 hours
//to heal all health.



//== How to Play
//
//At its core, the game is a conversation.
//One person plays as the Game Master (GM),
//and tells the other players what's happening
//in a shared fictional world.
//The other people describe what their characters
//a.k.a. Player Characters (PCs) do in response,
//and the GM describes how their actions impact the world.

//== Combat & Attacking
//
//When the GM introduces an enemy, they will describe it in detail.
//
//When you attack an enemy, describe how and where you try to hit it.
//The GM might ask to clarify what you're trying to accomplish with your attack.
//Either way, the GM will ask you to roll Strength (if using a melee weapon)
//or Dexterity (if using a ranged weapon) to see if you hit.
//If you damage the enemy, the GM will describe what happens.
//
//When you take damage, choose a stat to apply it to.
//Rolls with that stat are made with Disadvantage until it's healed.
//Damage can be healed with a Long Rest or certain magic items.
//
//If you take damage while all your stats are already damaged,
//you fall unconscious.
//If you take damage while unconscious, you die.
//
//Starting at 2nd level, you have Grit.
//Grit can be used to ignore damage.
//When taking damage, you can mark off a Grit space instead of an ability.
//Grit is healed with a Short Rest.
//
//Enemies and monsters don't have Health or Hit Points.
//Instead, they have limbs,
//
//Savage Worlds: Shaken > Wounded x4
//
//Blades in the Dark: Stress xN > Trauma
//
//grit > shield/armor > stat damage > hard moves (unconscious/dying)
//
//When a PC is wounded, the player chooses

