// unused maze rats tables
// * omens/magical catasrophes
// * clothing
// * after the party
// * dungeon entrances
// * dungeon layout

var adjectives = [
	"animating",
	"attracting",
	"binding",
	"blossoming",
	"consuming",
	"creeping",
	"crushing",
	"diminishing",
	"dividing",
	"duplicating",
	"enveloping",
	"expanding",
	"fusing",
	"grasping",
	"hastening",
	"hindering",
	"illuminating",
	"imprisoning",
	"levitating",
	"opening",
	"petrifying",
	"phasing",
	"piercing",
	"pursuing",
	"reflecting",
	"regenerating",
	"rending",
	"repelling",
	"resurrecting",
	"screaming",
	"sealing",
	"shapeshifting",
	"shielding",
	"spawning",
	"transmuting",
	"transporting",
	"avenging",
	"banishing",
	"bewildering",
	"blinding",
	"charming",
	"communicating",
	"compelling",
	"concealing",
	"deafening",
	"deceiving",
	"deciphering",
	"disguising",
	"dispelling",
	"emboldening",
	"encoding",
	"energizing",
	"enlightening",
	"enraging",
	"excruciating",
	"foreseeing",
	"intoxicating",
	"maddening",
	"mesmerizing",
	"mindreading",
	"nullifying",
	"paralyzing",
	"summoning",
	"intoxicating",
	"revealing",
	"terrifying",
	"maddening",
	"revolting",
	"warding",
	"mesmerizing",
	"scrying",
	"wearying",
	"mindreading",
	"silencing",
	"withering",
	"amphibious",
	"bloated",
	"brittle",
	"cannibal",
	"clay-like",
	"colossal",
	"crystalline",
	"decaying",
	"ethereal",
	"ever-young",
	"eyeless",
	"fearless",
	"fluffy",
	"fungal",
	"gelatinous",
	"geometric",
	"hardened",
	"illusory",
	"intelligent",
	"iridescent",
	"luminous",
	"many-headed",
	"mechanical",
	"planar",
	"reflective",
	"rubbery",
	"shadowy",
	"sharp",
	"skeletal",
	"slimy",
	"sticky",
	"stinking",
	"tiny",
	"translucent",
	"absorbing",
	"acid blood",
	"anti-magic",
	"blinding",
	//"{{ethereal element}}-breathing",
	"camouflaging",
	"duplicating",
	"electric",
	"entangling",
	"exploding",
	"flying",
	"gaze weapon",
	"hypnotizing",
	"impervious",
	"invisible",
	"life-draining",
	"magnetic",
	"mimicking",
	"mind-reading",
	"paralyzing",
	"phasing",
	"poisonous",
	"radioactive",
	"reflective",
	"regenerating",
	"shapeshifting",
	"spell-casting",
	"stealthy",
	"strangling",
	"super-strength",
	"telekinetic",
	"teleporting",
	"vampiric",
	"wall-crawling",
	"alien",
	"aloof",
	"bored",
	"cautious",
	"cowardly",
	"curious",
	"devious",
	"distractible",
	"educated",
	"embittered",
	"envious",
	"erudite",
	"fanatical",
	"forgetful",
	"generous",
	"hateful",
	"honorable",
	"humble",
	"jaded",
	"jovial",
	"legalistic",
	"manipulative",
	"megalomaniac",
	"melancholy",
	"meticulous",
	"mystical",
	"obsessive",
	"out of touch",
	"paranoid",
	"polite",
	"psychopathic",
	"sophisticated",
	"touchy",
	"unimpressed",
	"vain",
	"xenophobic",
	"altered",
	"ancient",
	"blessed",
	"bulky",
	"compact",
	"consumable",
	"culturally valuable",
	"cursed",
	"damaged",
	"disguised",
	"enemy-alerting",
	"embellished",
	"encoded",
	"exotic",
	"extraplanar",
	"famous",
	"forbidden",
	"fragile",
	"heavy",
	"immovable",
	"impractical",
	"indestructible",
	"intelligent",
	"masterwork",
	"militarily valuable",
	"non-human",
	"owned",
	"partial",
	"politically valuable",
	"religiously valuable",
	"repaired",
	"royal",
	"toxic",
	"vile",
	"bankrupt",
	"bureaucratic",
	"charitable",
	"confused",
	"connected",
	"corrupt",
	"decadent",
	"decaying",
	"delusional",
	"divided",
	"dwindling",
	"efficient",
	"esoteric",
	"expanding",
	"hunted",
	"incompetent",
	"incorruptible",
	"insane",
	"insular",
	"manipulative",
	"martial",
	"pious",
	"popular",
	"righteous",
	"ruthless",
	"secret",
	"subversive",
	"suppressed",
	"threatened",
	"thriving",
	"unpopular",
	"up-and-coming",
	"wealthy",
	"well-prepared",
	"xenophobic",
	"ashen",
	"blasted",
	"blighted",
	"broken",
	"consuming",
	"corrupted",
	"creeping",
	"desolate",
	"eternal",
	"forsaken",
	"frozen",
	"haunted",
	"howling",
	"jagged",
	"lonely",
	"misty",
	"perilous",
	"petrified",
	"phantasmal",
	"ravenous",
	"savage",
	"shadowy",
	"shifting",
	"shivering",
	"sinister",
	"sinking",
	"smoldering",
	"sweltering",
	"thorny",
	"thundering",
	"torrential",
	"wandering",
	"withered",
	"bellowing",
	"blazing",
	"bleak",
	"blessed",
	"bloody",
	"crimson",
	"cunning",
	"copper",
	"dancing",
	"dead",
	"drunken",
	"flying",
	"ghastly",
	"golden",
	"helpful",
	"hideous",
	"howling",
	"hungry",
	"moldy",
	"muttering",
	"nimble",
	"oozing",
	"petrified",
	"prancing",
	"romantic",
	"salty",
	"singing",
	"shivering",
	"shrieking",
	"silver",
	"smoking",
	"thirsty",
	"wicked",
	"tipsy",
	"whistling",
	"wanton"
]

// words that can be used as adjectives or nouns
var adjectnouns = [
	"acid",
	"amber",
	"bark",
	"blood",
	"bone",
	"brine",
	"clay",
	"crow",
	"crystal",
	"ember",
	"flesh",
	"fungus",
	"glass",
	"honey",
	"ice",
	"insect",
	"wood",
	"lava",
	"moss",
	"obsidian",
	"oil",
	"poison",
	"rat",
	"salt",
	"sand",
	"sap",
	"serpent",
	"slime",
	"stone",
	"tar",
	"thorn",
	"vine",
	"water",
	"wine",
	"wood",
	"worm",
	"ash",
	"chaos",
	"distortion",
	"dream",
	"dust",
	"echo",
	"ectoplasm",
	"fire",
	"fog",
	"ghost",
	"harmony",
	"heat",
	"light",
	"lightning",
	"memory",
	"mind",
	"mutation",
	"negation",
	"plague",
	"plasma",
	"probability",
	"rain",
	"rot",
	"shadow",
	"smoke",
	"snow",
	"soul",
	"star",
	"stasis",
	"steam",
	"thunder",
	"time",
	"void",
	"warp",
	"whisper",
	"wind",
	"aura",
	"beacon",
	"beam",
	"blast",
	"blob",
	"bolt",
	"bubble",
	"call",
	"cascade",
	"circle",
	"cloud",
	"coil",
	"cone",
	"cube",
	"dance",
	"disk",
	"field",
	"form",
	"gaze",
	"loop",
	"moment",
	"nexus",
	"portal",
	"pulse",
	"pyramid",
	"ray",
	"shard",
	"sphere",
	"spray",
	"storm",
	"swarm",
	"torrent",
	"touch",
	"vortex",
	"wave",
	"word",
	"alabaster",
	"amber",
	"aquamarine",
	"azurite",
	"beryl",
	"black pearl",
	"bloodstone",
	"bone china",
	"chalcedony",
	"cinnabar",
	"coral",
	"diamond",
	"ebony",
	"emerald",
	"fire agate",
	"garnet",
	"gold",
	"ivory",
	"jade",
	"jasper",
	"jet",
	"lapis lazuli",
	"malachite",
	"moonstone",
	"onyx",
	"opal",
	"pearl",
	"platinum",
	"porcelain",
	"ruby",
	"sapphire",
	"serpentine",
	"silver",
	"star iron",
	"topaz",
	"turqoise",
	"bog",
	"boulder field",
	"butte",
	"cave",
	"cliff",
	"crag",
	"crater",
	"creek",
	"crossing",
	"ditch",
	"field",
	"forest",
	"grove",
	"hill",
	"hollow",
	"hot springs",
	"lair",
	"lake",
	"lakebed",
	"marsh",
	"mesa",
	"moor",
	"pass",
	"pit",
	"pond",
	"rapids",
	"ravine",
	"ridge",
	"rise",
	"river",
	"rockslide",
	"spring",
	"swamp",
	"thickets",
	"valley",
	"waterfall"
]

var nouns = [
	"altar",
	"armor",
	"arrow",
	"beast",
	"blade",
	"cauldron",
	"chain",
	"chariot",
	"claw",
	"cloak",
	"colossus",
	"crown",
	"elemental",
	"eye",
	"fountain",
	"gate",
	"golem",
	"hammer",
	"horn",
	"key",
	"mask",
	"monolith",
	"pit",
	"prison",
	"sentinel",
	"servant",
	"shield",
	"spear",
	"steed",
	"swarm",
	"tentacle",
	"throne",
	"torch",
	"trap",
	"wall",
	"web",
	"albatross",
	"bat",
	"beetle",
	"songbird",
	"butterfly",
	"condor",
	"crane",
	"crow",
	"dragonfly",
	"eagle",
	"falcon",
	"firefly",
	"flamingo",
	"fly",
	"flying squirrel",
	"goose",
	"gull",
	"hummingbird",
	"kingfisher",
	"locust",
	"magpie",
	"mantis",
	"mockingbird",
	"mosquito",
	"moth",
	"owl",
	"parrot",
	"peacock",
	"pelican",
	"pteranodon",
	"rooster",
	"sparrow",
	"swan",
	"vulture",
	"wasp",
	"woodpecker",
	"ant",
	"ape",
	"armadillo",
	"badger",
	"bear",
	"boar",
	"caterpillar",
	"centipede",
	"chameleon",
	"cockroach",
	"deer",
	"elephant",
	"ferret",
	"fox",
	"giraffe",
	"goat",
	"horse",
	"human",
	"mole",
	"ostrich",
	"ox",
	"porcupine",
	"rabbit",
	"raccoon",
	"rat",
	"rhinoceros",
	"scorpion",
	"sheep",
	"slug",
	"snail",
	"snake",
	"spider",
	"squirrel",
	"tiger",
	"wolf",
	"wolverine",
	"alligator",
	"amoeba",
	"anglerfish",
	"beaver",
	"clam",
	"crab",
	"dolphin",
	"eel",
	"frog",
	"hippopotamus",
	"jellyfish",
	"leech",
	"lobster",
	"manatee",
	"manta ray",
	"muskrat",
	"narwhal",
	"newt",
	"octopus",
	"otter",
	"penguin",
	"platypus",
	"pufferfish",
	"salamander",
	"sea anemone",
	"sea urchin",
	"seahorse",
	"seal",
	"shark",
	"shrimp",
	"squid",
	"swordfish",
	"tadpole",
	"turtle",
	"walrus",
	"whale",
	"bowl",
	"brass bell",
	"brooch",
	"carved figurine",
	"cup",
	"deck of cards",
	"drawing",
	"foreign coin",
	"game piece",
	"glass eye",
	"glass jar",
	"hair comb",
	"handkerchief",
	"hinged box",
	"hourglass",
	"human tooth",
	"hunting horn",
	"loaded dice",
	"long fork",
	"numbered key",
	"oil lamp",
	"old doll",
	"paint pot",
	"pencil",
	"purse",
	"quill pen",
	"salve",
	"scissors",
	"scroll",
	"sealed letter",
	"sewing needle",
	"shaving razor",
	"silver button",
	"skull",
	"tobacco pipe",
	"wine bottle",
	"belt",
	"blouse",
	"boots",
	"bracelet",
	"breastplate",
	"brigandine",
	"cincture",
	"cloak",
	"coat",
	"dress",
	"earing",
	"eyepatch",
	"gauntlets",
	"glove",
	"gown",
	"hat",
	"helmet",
	"hose",
	"leather armor",
	"locket",
	"mail shirt",
	"mask",
	"necklace",
	"padded armor",
	"plate mail",
	"ring",
	"robe",
	"sandals",
	"scarf",
	"shirt",
	"shoes",
	"skirt",
	"slippers",
	"socks",
	"trousers",
	"veil",
	"arming sword",
	"backsword",
	"battleaxe",
	"blowpipe",
	"slaymore",
	"slub",
	"crossbow",
	"cutlass",
	"dagger",
	"flail",
	"flanged mace",
	"glaive",
	"halberd",
	"hammer",
	"hatchet",
	"horsebow",
	"hunting knife",
	"lance",
	"longbow",
	"longsword",
	"mace",
	"mail",
	"morningstar",
	"pike",
	"scimitar",
	"shortbow",
	"sickle",
	"sling",
	"spear",
	"staff",
	"stake",
	"stiletto",
	"throwing axe",
	"warhammer",
	"warpick",
	"whip",
	"acid flask",
	"bear trap",
	"bellows",
	"bolt-cutters",
	"chain",
	"chisel",
	"crowbar",
	"door ram",
	"ear trumpet",
	"fire oil",
	"fishing hook",
	"goggles",
	"grappling hook",
	"grease",
	"hacksaw",
	"hammer",
	"hand drill",
	"lantern",
	"lens",
	"lock/key",
	"lockpicks",
	"manacles",
	"metal file",
	"mortar/pestle",
	"needle",
	"pickaxe",
	"pitchfork",
	"pliers",
	"pole",
	"pulleys",
	"rope",
	"scissors",
	"shovel",
	"spikes",
	"steel wire",
	"tongs",
	"ancient liquor",
	"blind eye",
	"boiled cat",
	//"{{book}} page",
	"bottled fog",
	"coffin nail",
	"corpse's hair",
	"crossroad dust",
	"cultist entrails",
	"exotic spice",
	"killer's hand",
	"king's tooth",
	"last breath",
	"liar's tongue",
	"lightning bolt",
	"lodestone",
	"monk's vow",
	"newborn's cry",
	"oil portrait",
	"pyre ember",
	"queen bee",
	"queen's blood",
	"ship's barnacle",
	"star-metal",
	"thief's finger",
	"tomb flower",
	"wedding ring",
	"widow's tears",
	"wizard skull",
	"alchemy recipe",
	"amulet",
	"astrolabe",
	"blueprints",
	"calligraphy",
	"carpet",
	"compass",
	"contract",
	"crown",
	"crystal",
	"deed",
	"embroidery",
	"fine china",
	"fine liquor",
	"instrument",
	"magical book",
	"microscope",
	"music box",
	"orrery",
	"painting",
	"perfume",
	"prayer book",
	"printing block",
	"rare textile",
	"royal robes",
	"saint's relic",
	"scrimshaw",
	"sextant",
	"sheet music",
	"signet ring",
	"silverware",
	"spices",
	"spyglass",
	"tapestry",
	"telescope",
	"treasure map",
	"aristocracy",
	"art",
	"bureaucracy",
	"castes",
	"catacombs",
	"crime families",
	"cruelty",
	"festivals",
	"feuds",
	"intrigue",
	"martial law",
	"meritocracy",
	"opulence",
	"pilgrimages",
	"piracy",
	"plutocracy",
	"poverty",
	"rituals",
	"slavery",
	"spices",
	"theocracy",
	"thievery",
	"trade",
	"tyranny",
	"wizardry",
	"xenophobia",
	"assassination",
	"carnival",
	"conscription",
	"coronation",
	"coup",
	"cult activity",
	"curfew",
	"discovery",
	"earthquake",
	//"{{faction}} war",
	"fashion trend",
	"fire",
	"flood",
	"heavy fog",
	"heavy taxes",
	"holy day",
	"hysteria",
	"inquisition",
	"insurrection",
	"invasion",
	"jailbreak",
	"mass eviction",
	"mass pardon",
	"negotiations",
	"plague",
	"proclamation",
	"prohibition",
	"public games",
	"refugees",
	"rioting",
	"roundup",
	"scandal",
	"serial killer",
	"shortage",
	"tournament",
	"trial",
	"catacombs",
	"construction",
	"crafts",
	"criminality",
	"culture",
	"dining",
	"education",
	"entertainment",
	"finance",
	"foreigners",
	"ghettoes",
	"government",
	"graveyards",
	"green space",
	"industrialization",
	"judgement",
	"livestock",
	"marketplace",
	"memorials",
	"military",
	"opulence",
	"pollution",
	"poverty",
	"punishment",
	"religion",
	"science",
	"trade",
	"trash",
	"vices",
	"wizardry",
	"wonders",
	"academy",
	"alchemist",
	"archive",
	"art dealer",
	"barber",
	"bookbinder",
	"bookseller",
	"castle",
	"clockmaker",
	"clothier",
	"courthouse",
	"furrier",
	"gallery",
	"garden",
	"haberdashery",
	"jeweler",
	"law office",
	"locksmith",
	"lounge",
	"manor",
	"museum",
	"observatory",
	"opera house",
	"park",
	"physician",
	"printer",
	"public baths",
	"restaurant",
	"salon",
	"stables",
	"taxidermist",
	"temple",
	"tobacconist",
	"townhouse",
	"winery",
	"zoo",
	"apothecary",
	"asylum",
	"baker",
	"brewery",
	"butcher",
	"candlemaker",
	"catacombs",
	"cheesemaker",
	"criminal den",
	"curiosity shop",
	"dock",
	"fighting pit",
	"forge",
	"fortuneteller",
	"gambling hall",
	"leatherworks",
	"marketplace",
	"mason",
	"mill",
	"moneylender",
	"orphanage",
	"outfitter",
	"prison",
	"sewers",
	"shipyards",
	"shrine",
	"stockyard",
	"stonecarver",
	"tattooist",
	"tavern",
	"theater",
	"veterinarian",
	"warehouse",
	"watchtower",
	"weaver",
	"workshop",
	"arboretum",
	"atrium",
	"attic",
	"aviary",
	"ballroom",
	"baths",
	"bed chamber",
	"cabinet",
	"chapel",
	"cloakroom",
	"dining room",
	"dressing room",
	"garden",
	"garret",
	"greenhouse",
	"junk room",
	"kitchen",
	"larder",
	"library",
	"map room",
	"menagerie",
	"mews",
	"nursery",
	"pantry",
	"parlor",
	"privy",
	"root cellar",
	"saucery",
	"scullery",
	"smoking room",
	"spicery",
	"still room",
	"study",
	"trophy room",
	"wardrobe",
	"arcade",
	"awnings",
	"balconies",
	"barricades",
	"bridge",
	"canal",
	"carriages",
	"catwalks",
	"climbable walls",
	"clotheslines",
	"crowd",
	"dead end",
	"dense fog",
	"downpour",
	"flooding",
	"food stalls",
	"fountain",
	"gates",
	"ladders",
	"livestock",
	"muddy",
	"overgrown",
	"roof access",
	"roof gardens",
	"sewer access",
	"sinkhole",
	"slick",
	"steep roofs",
	"steep streets",
	"steps",
	"torn up street",
	"vermin swarms",
	"well",
	//"{{animal}} nests",
	"balconies",
	"basement access",
	"brightly lit area",
	"broken furniture",
	"broken glass",
	"cabinets",
	"carpeted floors",
	"chandeliers",
	"crawlspaces",
	"drain pipes",
	"dumbwaiters",
	"echoing marble",
	"hanging chains",
	"huge fireplace",
	"narrow ledges",
	"open windows",
	"ornate weapons",
	"overgrowth",
	"patrols",
	"piles of trash",
	"pillars",
	"rotting ceiling",
	"rotting floors",
	"rotting walls",
	"screens",
	"servant passages",
	"sewer access",
	"shadowy alcoves",
	"skylights",
	"spyholes",
	"staircases",
	"tall bookshelves",
	"unlit area",
	"watchdogs",
	"window drapes",
	"art movement",
	"beggar's guild",
	"black market",
	"brotherhood",
	"city guard",
	"conspiracy",
	"craft guild",
	"crime family",
	"crime ring",
	"dark cult",
	"explorer's club",
	"free company",
	"gourmand club",
	"heist crew",
	"heretical sect",
	"high council",
	"hired killers",
	"local militia",
	"national church",
	"noble house",
	"outlander clan",
	"outlaw gang",
	"political party",
	"religious order",
	"religious sect",
	"resistance",
	"royal army",
	"royal house",
	"scholar's circle",
	"secret society",
	"spy network",
	"street artists",
	"street gang",
	"street musicians",
	"theater troupe",
	"trade company",
	"ashy",
	"badlands",
	"bay",
	"beach",
	"delta",
	"desert",
	"dry lands",
	"dune sea",
	"dust bowl",
	"fjords",
	"flood lands",
	"foothills",
	"forest",
	"glaciers",
	"heath",
	"highlands",
	"hills",
	"ice fields",
	"jungle",
	"lowlands",
	"mesas",
	"moor",
	"mountains",
	"petrified forest",
	"plains",
	"rainforest",
	"ricerlands",
	"salt pan",
	"savanna",
	"steppe",
	"taiga",
	"thickets",
	"tundra",
	"volvanic plain",
	"wetlands",
	"woodlands",
	"altar",
	"aqueduct",
	"bandit's camp",
	"battlefield",
	"bonfire",
	"bridge",
	"cairn",
	"crossroads",
	"crypt",
	"dam",
	"dungeon",
	"farm",
	"ford",
	"fortress",
	"gallows",
	"graveyard",
	"hedge",
	"hunter's camp",
	"inn",
	"lumber camp",
	"mine",
	"monastery",
	"monument",
	"orchard",
	"outpost",
	"pasture",
	"ruin",
	"seclusion",
	"shack",
	"shrine",
	"standing stone",
	"temple",
	"village",
	"wall",
	"watchtower",
	"waystone",
	"blood stains",
	"bones",
	"broken weapons",
	"burrow",
	"cut ropes",
	"dead animal",
	"food scraps",
	"grave marker",
	"human corpse",
	//"lost {{npc}}",
	"magical effect",
	"map",
	"message",
	"migration",
	"nest",
	"portal",
	"resources",
	"rift",
	"strange plant",
	//"stunned {{npc}}",
	"supplies",
	"torn flag",
	"tracks",
	"trap",
	"treasure cache",
	"wizard fight",
	"avalanche",
	"blizzard",
	"brushfire",
	"bloudburst",
	"cyclone",
	"dense fog",
	"downpour",
	"drizzle",
	"dust storm",
	"earthquake",
	"eruption",
	"flooding",
	"forest fire",
	"hail",
	"heatwave",
	"hurricane",
	"ice storm",
	"light mist",
	"locust swarm",
	"magma flow",
	"meteor strike",
	"monsoon",
	"mudflow",
	"mudslide",
	"predator",
	"quicksand",
	"rain of frogs",
	"rockslide",
	"sandstorm",
	"sleet",
	"snow",
	"stampede",
	"thunderstorm",
	"tsunami",
	"whirlpool",
	"windstorm",
	"acorns",
	"apples",
	"asparagus",
	"blackberries",
	"blueberries",
	"carrots",
	"cattail",
	"cherries",
	"chickweed",
	"chicory",
	"clover",
	"dandelion",
	"dead-nettle",
	"elderberries",
	"fireweed",
	"gooseberries",
	"hazelnuts",
	"henbit",
	"hickory nuts",
	"honeysuckle",
	"leeks",
	"milk thistle",
	"mint",
	"mulberries",
	"mushrooms",
	"mustard",
	"onion",
	"pecans",
	"persimmons",
	"raspberries",
	"strawberries",
	"walnuts",
	"watercress",
	"wild garlic",
	"wild grapes",
	"wood sorrel",
	"angel's trumpet",
	"baneberry",
	"belladona",
	"black truffle",
	"bleeding heart",
	"celandine",
	"cocklebur",
	"columbine",
	"crowncup",
	"death cap",
	"dumbcane",
	"foxglove",
	"hemlock",
	"hogweed",
	"holly",
	"horse chestnut",
	"hyacinth",
	"ivy",
	"jessamine",
	"kudu",
	"larksur",
	"mandrake",
	"mangrove",
	"mistletoe",
	"moonflower",
	"nightshade",
	"oleander",
	"ragwort",
	"reindeer lichen",
	"snakeweed",
	"spinkle",
	"stinkhorn",
	"waxcap",
	"wine-cap",
	"wolfsbane",
	"wormwood",
	"axe",
	"barrel",
	"bear",
	"bell",
	"boot",
	"bowl",
	"bucket",
	"candle",
	"cock",
	"cow",
	"dragon",
	"egg",
	"elephant",
	"flea",
	"fork",
	"giant",
	"griffin",
	"hart",
	"hog",
	"hound",
	"lamb",
	"lion",
	"mackerel",
	"maid",
	"monk",
	"moon",
	"pipe",
	"prince",
	"rat",
	"skull",
	"spoon",
	"star",
	"swan",
	"sword",
	"whale",
	"wife",
	"arena",
	"asylum",
	"aviary",
	"bank",
	"baths",
	"body",
	"casino",
	"catacombs",
	"cave",
	"court",
	"forge",
	"garden",
	"hideout",
	"hoten",
	"laboratory",
	"library",
	"market",
	"mine",
	"monastery",
	"museum",
	"nursery",
	"orphanage",
	"palace",
	"prison",
	"sewer",
	"ship",
	"slave pit",
	"temple",
	"theater",
	"university",
	"vault",
	"zoo",
	"arcane disaster",
	"army invasion",
	"cannibalism",
	"civil war",
	"collapse",
	"crystal growth",
	"curse",
	"degeneration",
	"earthquake",
	"eruption",
	"evil unearthed",
	"experiments",
	"explosion",
	"famine",
	"fire",
	"flooding",
	"fungus",
	"haunting",
	"ice",
	"lava flow",
	"magical sleep",
	"melted",
	"monster attack",
	"outsider attack",
	"overgrowth",
	"petrification",
	"plague",
	"planar overlay",
	"poison gas",
	"resources gone",
	"revolt",
	"risen dead",
	"many traps",
	"war",
	"ancient lore",
	"animal ally",
	"army",
	"blessing",
	"blueprints",
	"cultural artifact",
	"faction ally",
	"forewarning",
	"guide",
	"holy relic",
	"influential ally",
	"instructions",
	"jewels",
	"key",
	"lost formula",
	"machine",
	//"magic {{item}}",
	"magical ally",
	"map",
	"marital ally",
	"masterpiece",
	//"{{monster}} ally",
	"oracle",
	"piles of loot",
	"planar portal",
	"prophecy",
	"renown",
	"spell",
	"transformation",
	"transport",
	"uncovered plot",
	"vision",
	"weapon",
	"armory",
	"banquet hall",
	"barracks",
	"catacombs",
	"cavern",
	"chasm",
	"courtyard",
	"crypt",
	"dormitory",
	"fighting pit",
	"forge",
	"fountain",
	"gate house",
	"guard room",
	"kennel",
	"laboratory",
	"mess hall",
	"mine shaft",
	"museum",
	"oubliette",
	"pool",
	"prison",
	"record room",
	"shrine",
	"slaughterhouse",
	"stables",
	"storeroom",
	"throne room",
	"torture room",
	"treasury",
	"vault",
	"well",
	"workshop",
	"bas-relief",
	"blood trail",
	"bones",
	"chains",
	"chalk marks",
	"claw marks",
	"corpses",
	"crached beams",
	"crumbling walls",
	"decaying food",
	"decaying nest",
	"dropping water",
	"fading murals",
	"faint breeze",
	"faint footsteps",
	"fallen pillars",
	"fungus",
	"furniture",
	"grafitti",
	"mosaics",
	"recent repairs",
	"rotting books",
	"rubble",
	"shed skin",
	"slime trails",
	"spider webs",
	"stalactites",
	"stench",
	"smoke stains",
	"thick dust",
	"torn clothes",
	"tree roots",
	"unusual smell",
	"vibrations",
	"vines",
	"whispers",
	"acid drip",
	"bloodsuckers",
	"cave-in",
	"choking dust",
	"crude oil",
	"crystal shards",
	"deafening noise",
	"dense fog",
	"ensnaring vines",
	"fallen floor",
	"flooding",
	"freezing",
	"geysers",
	"magma",
	"magnetic field",
	"mud flow",
	"narrow ledge",
	"narrow passage",
	"poison goo",
	"poison plants",
	"precipice",
	"quicksand",
	"radiation",
	"rockslide",
	"rotten ceiling",
	"rotten floor",
	"sinkhole",
	"slippery slope",
	"spider webs",
	"spores",
	"steam vents",
	"strong winds",
	"tar pit",
	"tight passage",
	"toppling object",
	"toxic fumes",
	"acid pool",
	"adhesive",
	"alarm",
	"armor-melting heat",
	"bear trap",
	"blinding spray",
	"blunt pendulum",
	"boiling tar",
	"collapsing floor",
	"crocodile pit",
	"crushing walls",
	"deep pit",
	"falling cage",
	"falling ceiling",
	"fills with sand",
	"flooding",
	"giant magnet",
	"hard vacuum",
	"lava flow",
	"lightning",
	"living statues",
	"missile fire",
	//"freed {{monster}}",
	"net trap",
	"pendulum blade",
	"poison gas",
	"poison needle",
	"quicksand",
	"rage gas",
	"rolling boulder",
	"room freeze trap",
	"room on fire",
	"sleeping gas",
	"spiked pit",
	"tomb-opening trap",
	"wall spikes"
]

var modifiers = [
	"that ages",
	"that attracts birds",
	"in child-form",
	"of corpulence",
	"covered in hair",
	//"with {{animal}} arms",
	//"with {{animal}} eyes",
	//"with {{animal}} head",
	//"with {{animal}} legs",
	//"with {{animal}} mouth",
	//"with {{animal}} skin",
	//"in {{animal}} form",
	"the cyclops",
	"with extra arms",
	"with extra eyes",
	"with extra legs",
	"with a forked tongue",
	"of genderswap",
	"the hunchback",
	//"in {{item}} form",
	"with long arms",
	"of hair loss",
	"of tooth loss",
	//"plus {{monster feature}}",
	//"plus {{monster trait}}",
	"with no eyes",
	"with no mouth",
	//"with {{physical element}} skin",
	"with a second face",
	"that sheds skin",
	"that shrinks",
	"that shrivels",
	"with skin boils",
	"with a slime trail",
	"with translucent skin",
	"that weeps blood",
	"that always lies",
	"that's always polite",
	//"that thinks it's in {{animal}} form",
	"that cannot count",
	"that cannot lie",
	"that's faceblind",
	"that fears birds",
	"that fears blood",
	"that fears books",
	"that fears darkness",
	"that fears fire",
	"that fears gold",
	"that fears horses",
	"that fears iron",
	"that fears music",
	"that fears own hand",
	"that fears a PC",
	"that fears rain",
	"that fears rivers",
	"that fears silence",
	"that fears sleep",
	"that fears sunlight",
	"that fears the moon",
	"that fears trees",
	"that thinks it's a genius",
	"that thinks it's gorgeous",
	"that hates violence",
	"that thinks it's invisible",
	"that thinks it's invulnerable",
	//"that thinks it has {{monster ability}}",
	//"that thinks it has {{monster feature}}",
	//"that thinks it has {{monster trait}}",
	"that must sing",
	//"with a new {{personality}}",
	"that says its thoughts",
	"that sees dead people",
	"with antlers",
	"with beak",
	"with carapace",
	"with claws",
	"with compound eyes",
	"with eye stalks",
	"with fangs",
	"with fins",
	"with fur",
	"with gills",
	"with hooves",
	"with horns",
	"the legless",
	"with long tongue",
	"the many-eyed",
	"the many-limbed",
	"with mucus",
	"with pincers",
	"with plates",
	"with plumage",
	"with proboscis",
	"with scales",
	"with segments",
	"with shaggy hair",
	"with shell",
	"with spikes",
	"with spinnerets",
	"with spines",
	"with stinger",
	"with suction cups",
	"with tail",
	"with talons",
	"with tentacles",
	"with trunk",
	"with tusks",
	"with wings",
	"that ambushes",
	"that calls for support",
	"that captures",
	"that charges",
	"that climbs foes",
	"that compels to worship",
	"that creates a barrier",
	"that deceives",
	"that demands duel",
	"that disorients",
	"that encircles",
	"that evades",
	"that gangs up",
	"that gathers strength",
	"that goes berserk",
	"that harries",
	"that hurls foes",
	"that immobilizes",
	"that manipulates",
	"that mocks",
	"that monologues",
	"that orders its minions",
	"that protects its leader",
	"that protects itself",
	"that scatters foes",
	"that stalks",
	"that steals",
	"that swarms",
	"that targets the insolent",
	"that targets the leader",
	"that targets the nearest",
	"that targets the richest",
	"that targets the strongest",
	"that targets the weakest",
	"that toys with its foes",
	"that uses terrain",
	"with a weakness to bells",
	"with a weakness to birdsong",
	"with a weakness to children",
	"with a weakness to cold",
	"with a weakness to cold iron",
	"with a weakness to competition",
	"with a weakness to conversation",
	"with a weakness to deformity",
	"with a weakness to flattery",
	"with a weakness to flowers",
	"with a weakness to gifts",
	"with a weakness to gold",
	"with a weakness to heat",
	"with a weakness to a holy icon",
	"with a weakness to holy water",
	"with a weakness to home cooking",
	//"with a weakness to {{insanities}}",
	"with a weakness to mirrors",
	"with a weakness to mistletoe",
	"with a weakness to moonlight",
	"with a weakness to music",
	//"with a weakness to {{methods}}",
	"with a weakness to phylactery",
	//"with a weakness to {{physical elements}}",
	"with a weakness to puzzles",
	"with a weakness to riddles",
	"with a weakness to rituals",
	"with a weakness to silver",
	"with a weakness to sunlight",
	"with a weakness to tears",
	"with a weakness to true name",
	//"with a weakness to {{valuable materials}}",
	"with a weak spot",
	//"with a weakness to {{weapon items}}",
	"with a weakness to wine",
	"with a weakness to wormwood",
	"of alchemy",
	"of art",
	"of astrology",
	"of blackmail",
	"of charts & maps",
	"of conspiracies",
	"of cookbook",
	"of criminals",
	"of divination",
	"of etiquette",
	"of fashion",
	"of genealogy",
	"of hagiography",
	"of history",
	"of journal",
	"of language",
	"of laws",
	"of letters",
	"of lost empires",
	"of lost places",
	"of love poems",
	"of monsters",
	"of mythology",
	"of odd customs",
	"of oratory",
	"of propaganda",
	"of prophecies",
	"of siegecraft",
	"of songs",
	"of state secrets",
	"of sword fighting",
	"of theology",
	"of treasures",
	"of war chronicle",
	"of who's who",
	"of witch-hunting",
	//"of {{animal}}-form",
	"of body swap",
	"of camouflage",
	"of control animals",
	//"of control {{element}}",
	"of cure affliction",
	"of detect evil",
	"of detect gold",
	"of detect hidden",
	"of direction sense",
	//"of {{element}}-form",
	//"of {{element}}-skin",
	"of the extra arm",
	"of flight",
	"of ghost-speech",
	"of heat vision",
	//"of {{insanity}}",
	"of invulnerable",
	//"of {{item}}-form",
	"of magic immunity",
	"of mirror image",
	//"of {{monster ability}}",
	//"of {{monster feature}}",
	//"of {{monster trait}}",
	//"of {{mutation}}",
	"of night vision",
	//"of random {{spell}}",
	"of restore health",
	"of speed",
	"of stretchy",
	"of super-jump",
	"of super-strength",
	"of telekinesis",
	"of tongues",
	"of water-breathing",
	"of water-walking",
	"that abducts",
	"that begs",
	"that brawls",
	"that burgles",
	"that celebrates",
	"that chases",
	"that constructs",
	"that cooks",
	"that dances",
	"that duels",
	"that executes",
	"that extinguishes",
	"that extorts",
	"that follows",
	"that gambles",
	"that hauls",
	"that interrogates",
	"that marries",
	"that mourns",
	"that parties",
	"that patrols",
	"that performs",
	"that plays",
	"that preaches",
	"that processes",
	"that proclaims",
	"that protests",
	"that releases",
	"that repairs",
	"that riots",
	"that robs",
	"that searches",
	"that sells",
	"wants to advise leader",
	"wants to avoid detection",
	"wants to awaken being",
	"wants to collect artifacts",
	"wants to construct base",
	//"wants to control {{faction}}",
	"wants to control politics",
	"wants to create artifact",
	"wants to create monster",
	//"wants to defeat {{faction}}",
	"wants to defend borders",
	"wants to defend leader",
	"wants to destroy artifacts",
	"wants to destroy being",
	"wants to destroy villain",
	"wants to enforce law",
	"wants to enrich members",
	"wants to entertain",
	"wants to exchange goods",
	"wants to hear rumors",
	"wants to indulge tastes",
	//"wants to infiltrate {{faction}}",
	"wants to map the wild",
	"wants to overthrow order",
	"wants to preserve lineage",
	"wants to preserve lore",
	"wants to produce goods",
	"wants to promote arts",
	"wants to promote craft",
	"wants to purge traitors",
	"wants to sell services",
	"wants to share knowledge",
	"wants to spread beliefs",
	"wants to sumon evil",
	"wants to survive",
	"wants to transport goods",
	"that ambushes",
	"that argues",
	"that births",
	"that builds",
	"that buries",
	"that captures",
	"that convenes",
	"that demolishes",
	"that dies",
	"that duels",
	"that eats",
	"that excavates",
	"that feasts",
	"that fells",
	"that fishes",
	"that flees",
	"that forages",
	"that hunts",
	"that marches",
	"that raids",
	"that rescues",
	"that rests",
	"that sacrifices",
	"that scouts",
	"that sings",
	"that skins",
	"that skirmishes",
	"that slays",
	"that sleeps",
	"that swims",
	"that tracks",
	"that traps",
	"that wanders",
	"that worships",
	"that's from 100 years in the past",
	"that's always night",
	"with animal fights",
	"with bard duels",
	"that's bigger on the inside",
	"with a black market",
	"that's brand new",
	"with cannibals",
	"with a constant party",
	"with a dancing contest",
	"that's a dead drop",
	"that's expensive",
	//"that's a {{faction}} hangout",
	"with a famous chef",
	"with fey patrons",
	"that's a fight club",
	"five floors tall",
	"with ghost staff",
	"that's haunted",
	"that's a hideout",
	//"that's an inn/{{buildling}}",
	"with a magic sword",
	"that magically moves",
	"with mercenaries for hire",
	//"that's an {{npc}} hangout",
	"with preaching",
	"that has secure storage",
	"with staff that are kids",
	"with a talking painting",
	"that's underground",
	"with a VIP lounge",
	"with a voice in a well",
	"for women only",
	"that besieges",
	"that captures",
	"that collects",
	"that constructs",
	"that controls",
	"that delivers",
	"that demolishes",
	"that escapes",
	"that feeds",
	"that fortifies",
	"that guards",
	"that hides",
	"that hunts",
	"that loots",
	"that maps",
	"that mines",
	"that negotiates",
	"that patrols",
	"that performs ritual",
	"that purges",
	"that questions",
	"that raids",
	"that repairs",
	"that rescues",
	"that researches",
	"that revives",
	"that riddles",
	"that scavenges",
	"that seizes",
	"that tunnels",
	"that unearths",
	"that vanalizes",
	"that worships",
	"of absorption",
	"of activation",
	"of animation",
	"of blessings",
	"of communication",
	"of confusion",
	"of consumption",
	"of creation",
	"of curses",
	"of deception",
	"of duplication",
	"of exchange",
	"of imprisonment",
	"of instructions",
	"of interrogation",
	"of mind-control",
	"of mood-alteration",
	"of nullification",
	"of planeshift",
	"of protection",
	"of rejuvenation",
	"of release",
	"of reversal",
	"of rotation",
	"of scrying",
	"of size-alteration",
	"of summoning",
	"of theft",
	"of time-alteration",
	"of transformation",
	"of transmutation",
	"of transportation",
	"of wonder",
	"activated by blowing",
	"activated by breaking",
	"activated by burning",
	"activated by a choice",
	"activated by a countdown",
	"activated by darkness",
	"activated by draining",
	"activated by eating",
	"activated by inserting",
	"activated by killing",
	"activated by knocking",
	"activated by light",
	"activated by magic",
	"activated by melody",
	"activated by noise",
	"activated by opening",
	"activated by a phrase",
	"activated by pouring",
	"activated by pressing",
	"activated by proximity",
	"activated by pulling",
	"activated by reading",
	"activated by reflection",
	"activated by releasing",
	"activated by removing",
	"activated by retrieving",
	"activated by rudeness",
	"activated by shutting",
	"activated by sitting",
	"activated by sleeping",
	"activated by sliding",
	"activated by touching",
	"activated by turning",
	"activated by unbalancing",
	"activated by unearthing",
	"activated by writing"
]

/**
 * Returns a random integer between min (inclusive) and max (inclusive)
 * Using Math.round() will give you a non-uniform distribution!
 */
function randomint(min, max) {
    return Math.floor(Math.random() * (max - min + 1)) + min;
}

function randomitem(list) {
	return list[Math.floor(Math.random()*list.length)];
}

// generates a thing of the form
// adjective [adjective|adjectnoun] noun|adjectnoun [modifier]
function thinggen() {
	var retval = "";

	if (randomint(0,1) == 1) {
		adjective = randomitem(adjectives);
		retval = retval.concat(" ", adjective);
	}

	var adjective = randomitem(adjectives.concat(adjectnouns));
	retval = retval.concat(" ", adjective);

	var noun = randomitem(nouns.concat(adjectnouns));
	retval = retval.concat(" ", noun);

	if (randomint(0,1) == 1) {
		var modifier = randomitem(modifiers);
		retval = retval.concat(" ", modifier);
	}

	return retval.concat("<br/>");
}

function main() {
	//document.getElementsByTagName("code")[0].innerHTML=genCharacter();
	//document.getElementsByTagName("code")[1].innerHTML=genCharacter();
	//document.getElementsByTagName("code")[2].innerHTML=genCharacter();
	//document.getElementsByTagName("code")[3].innerHTML=genCharacter();
	var things = document.getElementsByClassName("thing");
	for(var i = 0; i < things.length; i++) {
		things.item(i).innerHTML=thinggen();
	}
}

//window.onload = main;

